# Generated by Django 5.2.4 on 2025-08-01 22:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="Unique identifier for this plan (e.g., 'free', 'pro', 'enterprise')", unique=True)),
                ('name', models.CharField(help_text="Display name for the plan (e.g., 'Pro Plan')", max_length=50)),
                ('description', models.TextField(blank=True, help_text='Optional description of the plan and its features.')),
                ('api_quota', models.PositiveIntegerField(help_text='Maximum number of API calls allowed per period.')),
                ('period_days', models.PositiveIntegerField(default=30, help_text='Number of days after which quota resets (default: 30 days).')),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
                'ordering': ['api_quota'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('api_key', models.CharField(editable=False, max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the subscription is active or not.')),
                ('usage_count', models.PositiveIntegerField(default=0, help_text='Number of API calls used in the current period.')),
                ('reset_at', models.DateTimeField(help_text='Date and time when the current period will reset.')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='subscriptions.plan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subscription Profile',
            },
        ),
    ]
